; MOV ADD SUB

MOV REGISTER,DATA
MOV REGISTER,REGISTER
MOV REGISTER,MEMORY UNIT
MOV MEMORY UNIT,REGISTER
MOV REGISTER,MEMORY UNIT
MOV SEGMENT REGISTER,GEGISTER
MOV REGISTER,SEGMENT REGISTER

; ADD like MOV, but it can't operate the segment register